Fix logrotate access denied by shipping modified logrotate script
Logrotate failed on MySQL logs with the following error message:
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
error: error running shared postrotate script for '/var/log/mysql/mysql.log

Due to the fact that $HOME is not set in logrotate environment, mysqladmin
does not read /root/.my.cnf (mysql config file for root) where the login
credentials are provided.

This patch fixes it.